title: ""
description: "Sec notes by Guanxing"
baseurl: ""
url: "https://hhj4ck.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  social_links:
    - title: Guanxing
      icon: x-twitter
      url: "https://x.com/hhj4ck"

