title: ""
description: "Sec notes by Guanxing"
baseurl: ""
url: "https://hhj4ck.github.io"

theme: minima            # 也可换 jekyll-theme-cayman 等
plugins:
  - jekyll-feed         # RSS 自动生成
  - jekyll-seo-tag      # SEO 与社媒卡片

# Minima Theme social links
minima:
  social_links:
    twitter: hhj4ck
    github:  hhj4ck

