title: ""
description: "Sec notes by Guanxing"
baseurl: ""
url: "https://hhj4ck.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  social_links:
    - platform: twitter
      user_url: "https://x.com/hhj4ck"
      title: "Guanxing on X"
